### ISSUE TITLE
Non-breaking spaces to protect short terms

### ISSUE THREAD

**Issue by tillheilmann** [citation-style-language/locales#100]
How about protecting short terms like "o. A." ("anonymous" in German locale) with non-breaking spaces, to prevent line breaks? I could do this for the German locale files.

**Comment by adam3smith** [comment]
I don't have a general objection, but is this a general rule in German not to insert line breaks between parts of an interruption? Do we have a reference for that? 
(This is an honest question: e.g. for page ranges, this is a rule in French, but not in English)

**Comment by tillheilmann** [comment]
Reference is Friedrich Forssman/Ralf de Jong: Detailtypografie, 4. Aufl., Mainz: Hermann Schmidt 2008, p. 133: "Abkürzungen werden nie getrennt. […] Alle Abkürzungen mit Binnenpunkt müssen innerhalb der Abkürzung mit einem gFL [= geschütztes flexibles Leerzeichen; T.A.H.] versehen werden." Examples given for this are: "a. a. O. / am angegebenen Ort; d. h. / das heißt; m. E. / meines Erachtens […]"

**Comment by adam3smith** [comment]
wunderbar. Nehme dann gerne das pull request for de-DE/AT/CH

If anyone knows of similar typographic rules detailed for other languages, that'd be great. You'd think that typography is international, but our experience has been that it's very much not.
