### ISSUE TITLE
[Swedish] Error in ordinals

### ISSUE THREAD

**Issue by perenstrom** [citation-style-language/locales#109]
Ordinals in Swedish are written with a colon after the number, and before the ordinal character. 

Reference: Ola Karlsson (red). 2008. Svenska skrivregler (Rules for writing in Swedish), p. 161. 3rd edition. Liber, Stockholm.

**Comment by adam3smith** [comment]
could you give an example to make sure we get this right?

**Comment by inukshuk** [comment]
Ideally we would add tests like [we are currently using for other languages](https://github.com/inukshuk/csl-ruby/blob/master/features/locales/ordinalize.feature), so a list of examples would be much appreciated.

**Comment by perenstrom** [comment]
Basically all numbers ending in 1 or 2 should have ":a" as the suffix and all others should have ":e".
1 - 1:a
2 - 2:a
3 - 3:e
4 - 4:e
...

*1 and *2 could have ":e" when the word is masculine. But this is an edge case (not relevant for common words such as edition, etc) and is losing traction in the language.

**Comment by inukshuk** [comment]
This is great, thanks!

Out of curiosity, is this a mistake: '11:a', but 'elfte' (not 'elfta') and '12:a', but 'tolfte' (not 'tolfta') or are 11, 12 different than the others?

**Comment by inukshuk** [comment]
[Here](https://github.com/inukshuk/csl-ruby/blob/master/features/locales/ordinalize.feature#L640) are the updated tests including Swedish. Can you quickly review the examples in the table to make sure I got them right?

@adam3smith do you want me to update the locale?

**Comment by adam3smith** [comment]
Yes, Please. (Still travelling, will be back To normal schedule Next Week.)

**Comment by rmzelle** [comment]
https://en.wikipedia.org/wiki/Swedish_grammar#Numerals shows 11:e and 12:e. Not consistent with https://en.wikipedia.org/wiki/Ordinal_indicator#Other_languages, though, but consistent with http://broadcast.lds.org/elearning/FHD/Community/FHL/Handwriting/ScandinavianGothic/Lesson_2/ScandinavianOrdinalNumbers.pdf.

**Comment by perenstrom** [comment]
Crap, knew I would get some wrong. Got kind of number and letter blind after a while. It is indeed 11:e and 12:e (exception to the rule of 1 and 2 having :a). Fixed my Drive-link.

@inukshuk, it looks correct except "german" in the beginning and 11 and 12 as mentioned.

The gendered forms apply for 21, 22, 31, 32, etc. as well.

**Comment by inukshuk** [comment]
@perenstrom thanks! Can you [look at the tests](https://github.com/inukshuk/csl-ruby/blob/master/features/locales/ordinalize.feature#L640) one more time just to be on the save? I added a few more of the interesting cases to make sure we get them right, e.g. 101 102, 111, 112, 31, 32 etc.

**Comment by perenstrom** [comment]
Looks stellar!

**Comment by rmzelle** [comment]
Just accepted #110. @perenstrom, thanks for reporting!
