### ISSUE TITLE
Use fol./fols(.) for short form of 'folio' term?

### ISSUE THREAD

**Issue by adunning** [citation-style-language/locales#115]
CMoS (14.162, 14.235) and MHRA both give 'fol.', plural 'fols' (with period in en-US, often omitted in en-GB) rather than the CSL 'f.', which occurs but is unusual. Should this be changed?

**Comment by adam3smith** [comment]
in general yes -- quesiton is where. I'd say if this is both Chicago and MHRA, we should just change it in the locale. 
We could consider doing the plural w/o period in en-GB. @rmzelle what do you think?

**Comment by rmzelle** [comment]
Do any of the current styles redefine this term? I agree with "fol/fols". Just an "f" seems ambiguous.

**Comment by adam3smith** [comment]
yes, a couple:
grep -l term\ name=\"folio\" *.csl
chicago-author-date-basque.csl
irish-historical-studies.csl
jahrbuch-der-osterreichischen-byzantinischen-gesellschaft.csl
journal-of-neurochemistry.csl
medical-history.csl
modern-humanities-research-association-author-date.csl
modern-humanities-research-association.csl
past-and-present.csl
u-schylku-starozytnosci.csl

some of these probably don't define the English one, though.

**Comment by adam3smith** [comment]
Also, what do you think about the period? Should we do it w/o period in the plural in en-GB?

**Comment by adunning** [comment]
The rest of the en-GB file uses periods (e.g. 'vols.'), but it's not clear to me whether there is a technical reason for this, or whether it's an oversight. The most common practice in British usage (see e.g. MHRA, New Hart’s Rules) would write 'fols', 'vols', 'cols', 'eds', etc. without the period, the rationale being that these are all contractions: the exceptions are 'no.' and 'nos.' for the sake of clarity.

**Comment by rmzelle** [comment]
The reason we prefer to have periods in locale file terms is that removing periods is much easier to automate than adding them. (since the computer doesn't know which terms are abbreviations, and which aren't)

Leaving out the periods is only a good idea if you're positive that a term (almost) never uses periods.

**Comment by adam3smith** [comment]
the problem here, though, is that only the plural term doesn't, so strip-periods doesn't work. I've usually redefined these in the style, i.e.
```
<term name="editor" form="short">
  <single>ed.</single>
  <multiple>eds</multiple>
</term>
```
My problem with redefining this would be that we'd have to check all existing en-GB styles because while this is common, it is not universal. Might still be worth it, but there are 240 of them...

**Comment by rmzelle** [comment]
Ah, right.

> My problem with redefining this would be that we'd have to check all existing en-GB styles

Check them for what? I would just check those that redefine the "folio" term, which according to your list above is only a handful.

**Comment by adam3smith** [comment]
that was referring to doing this for all short terms as per
> The most common practice in British usage (see e.g. MHRA, New Hart’s Rules) would write 'fols', 'vols', 'cols', 'eds', etc. without the period, the rationale being that these are all contractions

I think switching to fol./fols. en-US and fol./fols en-GB is unproblematic.

**Comment by adam3smith** [comment]
(no need for Pull request, I'll just do that).

**Comment by adunning** [comment]
Awesome; thank you!

For consistency, did we also want to change the other contraction terms for en-GB?

**Comment by adam3smith** [comment]
For the purely locator terms, I see no issue with that--currently we don't specify a plural for those at all. 
But for other terms liked ed./eds, that's exactly the concern expressed above: while you're absolutely correct that the more common UK form in the plural w/o period, the regular eds. _does_ exist and we'd with one strike break all en-GB styles that rely on that if we were to change it. So ideally we'd have to go through them and check, but there are a lot of them--I didn't realize almost 1/4 of our styles were en-GB

**Comment by adunning** [comment]
Yes, that's definitely the safest course; I would not have guessed that. Do you want me to submit a pull request for the locator terms?

**Comment by adam3smith** [comment]
yes, please do. While you're at it, would you mind also adding the plurals
(with period) to en-US where they're oddly absent.

On Wed, Sep 16, 2015 at 7:14 PM, Andrew Dunning <notifications@github.com>
wrote:

> Yes, that's definitely the safest course; I would not have guessed that.
> Do you want me to submit a pull request for the locator terms?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/citation-style-language/locales/issues/115#issuecomment-140930678>
> .
>



-- 
Sebastian Karcher, PhD
www.sebastiankarcher.com
