### ISSUE TITLE
Multiple translations of 'et al.'

### ISSUE THREAD

**Issue by 5ke** [citation-style-language/locales#123]
Hi, 
This issue is somewhat related to issue #6. There seems to be some disagreement whether one should translate 'et al.' to 'mfl.', 'm.fl.' or just simply 'et al.' in Norwegian. 
I'm not going to argue about which one is right, because I expect different fields have different habits anyways.

Is there any way by which multiple 'et al.' translations can be added to the locale sheet in such a way that the user of a specific style gets to pick the one that suits him/her best?

**Comment by adam3smith** [comment]
Beyond the et al./and others distinction there is no way to add multiple translations of the same term to a style, no. The situation you describe is not at all uncommon: even in English, for example, we see different abbreviations for edition (ed. and edn.), German has the same issue with using both et al. and its German translation, etc.

The place to adjust this is the citation style itself. You can override global term definitions in citation styles using (e.g.)

```
<locale xml:lang="nn-NO">
  <terms>
    <term name="et-al">et al.</term>
  </terms>
</locale>
```

to change mfl. to et al. Letting style users pick individual terms is certainly not something we'd want to do in CSL. If there's high demand, reference managers could certainly implement some version of this (where they offer you to override existing terms), but given how long it has taken them to even implement proper locale support, I very much doubt that's something they're interested in.

**Comment by 5ke** [comment]
Ok, I was afraid that it would be like that. Thank you for your reply though :-)

**Comment by rmzelle** [comment]
(so currently, we always try to use the most common translation of each term in the locale files, while allowing individual styles to define overriding translations.)
