### ISSUE TITLE
[de-AT] add some missing translations

### ISSUE THREAD

**Issue by georgd** [citation-style-language/locales#125]
A few strings are in English. The attached patch fixes them. I also added the term for »collection-editor« so de-AT will show the same features as de-DE.

[gduffner_patch001.patch.txt](https://github.com/citation-style-language/locales/files/66630/gduffner_patch001.patch.txt)

**Comment by rmzelle** [comment]
Would you mind creating a pull request? It's an easy process (https://help.github.com/articles/editing-files-in-another-user-s-repository/), and it makes things much easier to review for us.

**Comment by georgd** [comment]
Ok, I’ll create a pull request later (just learnt how easy it is in the style commit explanation) :)

**Comment by rmzelle** [comment]
It should be easier, yes :). You're actually the first person to submit a patch file since we moved to GitHub in 2011.

**Comment by rmzelle** [comment]
(continued in #126)
