### ISSUE TITLE
`presented at` contains an article which is applicable to only some reference styles

### ISSUE THREAD

**Issue by danwchan** [citation-style-language/locales#175]
I have noticed that the term `presented at` contains the article "the" in English and "der" in German. This seems to be only required in some citation styles such as APA and Chicago while styles like AMA and NLM uses a colon instead of the article.

I'm not sure if this can be fixed easily but I figured I would log it as an issue in case it produces some useful discussion.

**Comment by adam3smith** [comment]
You can modify terms in the beginning of a style http://docs.citationstyles.org/en/stable/specification.html#locale and you can do so for multiple languages.
This will often be necessary as small variation exist between how a given term is used in citation styles.

**Comment by adam3smith** [comment]
I'm agnostic on whether it's better to have or not have the article in the default locale files, but it's probably easier to leave as is now. 

OK to close this?

**Comment by danwchan** [comment]
Makes sense to me.
