### ISSUE TITLE
How to include two language in Bibliography?

### ISSUE THREAD

**Issue by CangHaiQingYue** [citation-style-language/locales#185]
Hi, Thanks for your time, I have a problem in changing lauguage.
My Bibliography includes two language, 'en' and 'zh-CN', how can I change them adaptable？

**Comment by fbennett** [comment]
There would be two ways to do this, each with different advantages and disadvantages.

(1) If you put the items that you cite into a Zotero collection, you can export two copies of the bibliography from the collection (not in the document, but in Zotero itself). Then you can produce a mixed copy of the bibliography, by hand, copying and pasting the entries. When finished, the mixed bibliography can be inserted into your document. The advantage is that you can do this right away, without special preparation. The disadvantage is that manual editing is required---and this method will not adapt language settings in citations.

(2) With [Juris-M](https://juris-m.github.io/), a multilingual variant of Zotero, it is possible to combine two separate styles, applied according to language. The advantage of that approach is that a properly formatted mixed-format bibliography can be generated automatically. The disadvantage is that all cited items must be properly tagged for language (in accordance with IETF BCP 47), and the combined style itself needs to be built.

**Comment by rmzelle** [comment]
(as @fbennett is already alludes to, there is currently no native support for per-item localization in CSL-generated bibliographies, but you can use one of the workaround above. Adding official support is high on our todo list for the next CSL release.)

**Comment by CangHaiQingYue** [comment]
Thanks a lot! @fbennett @rmzelle
