### ISSUE TITLE
[Slovenian] Wrong translation of short "et al" and there is no sign "&" in slovenian, should be "in"

### ISSUE THREAD

**Issue by frilancer** [citation-style-language/locales#194]
For short translation of "et al." in Slovenian language, the correct translation would be "idr.", which would correspond to "and others" which is translated correctly as "in drugi".

Not sure if this bit belongs here, but there is no "&" sign in Slovene, and when quoting in APA6 style, for instance "(Perls, Hefferline & Goodman, 1994)" is not correct. Correct way would be "(Perls, Hefferline in Goodman, 1994)"

**Comment by rmzelle** [comment]
Thanks.

> For short translation of "et al." in Slovenian language, the correct translation would be "idr.", which would correspond to "and others" which is translated correctly as "in drugi".

@KrOstir, could you give me your opinion here? You proposed changing "in dr." to "in sod." last year (https://github.com/citation-style-language/locales/pull/179).

> Not sure if this bit belongs here, but there is no "&" sign in Slovene, and when quoting in APA6 style, for instance "(Perls, Hefferline & Goodman, 1994)" is not correct. Correct way would be "(Perls, Hefferline in Goodman, 1994)"

There is a long-standing ticket to make the ampersand symbol localizable (https://github.com/citation-style-language/locales/issues/70), which is necessary to properly address this. Right now the only solution is to edit the CSL style to not use the ampersand symbol.

**Comment by KrOstir** [comment]
There is not an agreement on how to translate et al. to Slovenian. Some organizations/publishers use "idr." the others "in sod." and many just "et al."

The original "in dr." does not exist as an abbreviation, but "idr." does and I agree with the change.

**Comment by rmzelle** [comment]
Okay, thanks both. I changed the translation of "et al." from "in sod." to "idr." just now.

The ampersand issue is logged in another issue, so I'll close this one.
