### ISSUE TITLE
[Slovenian] APA incorrect bibliography entry when citing document with URL

### ISSUE THREAD

**Issue by peroxy** [citation-style-language/locales#200]
Using APA (American Psychological Association 6th edition) with citation and bibliography language set to English, we have a bibliography entry that looks like this:

> CSL search by example. (n.d.). Retrieved December 15, 2012, **from** http://editor.citationstyles.org/searchByExample/

If we change the language to Slovenian, we now get a bibliography entry that looks like this:

> CSL search by example. (b. d.). Pridobljeno 15. december 2012, **od** http://editor.citationstyles.org/searchByExample/

From is correct in English, but not in Slovenian. It should be `s` instead of `od`, this is the correct version of it:

> CSL search by example. (b. d.). Pridobljeno 15. december 2012, **s** http://editor.citationstyles.org/searchByExample/

Here is a guide by University of Ljubljana that explains how to make APA citations, if you scroll down you have a few examples that confirm my issue: http://vodici.pef.uni-lj.si/subjects/guide.php?subject=citiranje

I have fixed this issue locally by editing locales-sl-SI.xml and changing the `from` term:
`<term name="from">s</term>`
I do not know if the term from is used anywhere else and if this is a proper solution, it feels more like a hack as `from` does indeed translate to `od`, while `s` would actually translate to `with`. I've created a PR with my change.

**Comment by peroxy** [comment]
Is this repo dead?

**Comment by adam3smith** [comment]
No, sorry, this just slipped through. Would "od" every be used for a URL in Slovenian (in other citation styles say?). I'm pretty sure "from" is used almost exclusively to specify the location of material in an archive or at a URL. If that's better covered by "s" in Slovenian, we can switch it, otherwise we'd want to limit the switch to the APA styles (which is also possible)

**Comment by peroxy** [comment]
No, “od” should never be used for a URL in Slovenian, it really should be
switched everywhere if it’s exclusively used for URL and archive.

Dne sre., 6. maj 2020 ob 22:31 je Sebastian Karcher <
notifications@github.com> napisal/-a:

**Comment by adam3smith** [comment]
Thanks & sorry for the long wait!
