### ISSUE TITLE
How CSL file fetches the data in the local file?

### ISSUE THREAD

**Issue by TomBener** [citation-style-language/locales#213]
Locale files are useful, but the common local files are not "common" sometimes.

<img width="871" alt="截屏2021-01-11 22 58 47" src="https://user-images.githubusercontent.com/49151155/104199764-d3179b80-5462-11eb-8b68-d828c864636b.png">

For example, we use quotation marks `“”` and `‘’` sometimes in Chinese, not `《》` and `〈〉` all the time. While the common local files in the figure below is arbitrary for this kind of usage.

<img width="560" alt="截屏2021-01-11 22 59 24" src="https://user-images.githubusercontent.com/49151155/104199811-df035d80-5462-11eb-9f8e-45ee0f4f5d08.png">

And the local file is at https://github.com/citation-style-language/locales/blob/master/locales-zh-CN.xml

Due to the quotation mark in the local file, the bibliography with quotations like “” would be converted as 《》, while I actually want is the original `“”`.

For instance, the output is like:

<img width="721" alt="截屏2021-01-11 23 18 26" src="https://user-images.githubusercontent.com/49151155/104200198-5638f180-5463-11eb-9fec-0d7e29653151.png">

And in BibTeX file it’s like:

```
@article{caijingjing2011,
  title = {“分山到户”或“共有产权”：集体林权制度改革的社会—生态关键变量互动分析——以福建省5个案例村为例},
  author = {{蔡晶晶}},
  date = {2011},
  journaltitle = {经济社会体制比较},
  pages = {154--160},
  number = {06}
}
```
Although the issue could be resolved by changing the `default-locale` to `en-US`, I still have a question, when I set `default-locale` as a specific language like `zh-CN` in the CSL file. Then how the CSL file fetches the data from the local translation, it's from the GitHub URL or local file on my disk? Thanks!

**Comment by adam3smith** [comment]
You can override specific terms in a global locale in a given CSL file, see https://docs.citationstyles.org/en/stable/specification.html#locale
Where locales are drawn from is at the level of the citation processor or reference manager, not the CSL file so the answer to this is 'it depends'. Zotero downloads locale files with every new version, for example, so those are local.

**Comment by TomBener** [comment]
@adam3smith Thanks for your reply.

There is not the issue on the quotation mark if I use Zotero for Word to insert references in `.docx` files.

But I usually use [Pandoc](https://pandoc.org/) for conversion. So I added the code below in this [CSL file](https://github.com/citation-style-language/styles/blob/master/china-national-standard-gb-t-7714-2015-author-date.csl#L22) at line 22:

```xml
<term name="open-quote">“</term>
<term name="close-quote">”</term>
<term name="open-inner-quote">‘</term>
<term name="close-inner-quote">’</term>
```

But it didn’t work with the output via Pandoc. I’v no idea the issue was caused by CSL files or Pandoc. How could I fix it? Thank you!

**Comment by adam3smith** [comment]
I don't know how pandoc handles locale files. I'd guess they're downloaded from github at the time of conversion, but I'm really just guessing. I think there's a google group where you could ask?

Closing this since it sounds like your issue has been fixed.

**Comment by TomBener** [comment]
@adam3smith Thanks you!

**Comment by TomBener** [comment]
BTW, could you help to figure out where is the local files of Zotero? I'd like to edit it for my personal use.

**Comment by fbennett** [comment]
You won't want to edit the locale files in Zotero itself. Just customize the CSL styles that you use with appropriate overrides, as you have done above.

**Comment by TomBener** [comment]
@fbennett Yes, you’re right. But I'd like to figure out why Zotero for Word does not has the same issue of quotation mark as I mentioned above:

> There is not the issue on the quotation mark if I use Zotero for Word to insert references in `.docx` files.

If Zotero and Pandoc both use the same [local file](https://github.com/citation-style-language/locales/blob/master/locales-zh-CN.xml), they should have the same issue, but Zotero doesn’t. I'm curious about the cause.

**Comment by fbennett** [comment]
The Zotero client uses the locale files maintained by the CSL project. (The "csl" link in the Zotero source is just [a pointer](https://github.com/zotero/zotero/tree/master/chrome/content/zotero/locale) into the CSL repository). The difference in behavior that you see is probably due to the citation processors in Zotero and Pandoc. The former normalizes quotation marks in the content of input fields; if the Pandoc processor leaves quotation marks in field content untouched, that would account for the difference that you see.

**Comment by TomBener** [comment]
@fbennett Thanks for your kind reply, really useful!
