### ISSUE TITLE
CI: Don't fail when adding a new locale

### ISSUE THREAD

**Issue by neha-sri** [citation-style-language/locales#217]
Hello, I have submitted a PR for adding Hindi (India) in #216. The build is failing because there is no entry for hi-IN in `locales.json`. 

```
1) The file "locales.json" must define a primary dialect for every language (e.g. "de-DE" for "de")
     Failure/Error: expect(@locale_file_languages - @primary_dialects.keys).to eq([])
 2) The file "locales.json" must define language names for every locale
     Failure/Error: expect(@locale_file_locales - @language_names.keys).to eq([])
```

But when we add the expected changes to locales.json, the build fails because it doesn't expect that file in the PR. 

```
bundler: failed to load command: sheldon (/home/runner/work/locales/locales/vendor/bundle/ruby/2.7.0/bin/sheldon)
RuntimeError: Unexpected locales file locales.json in pull request
```

Please simplify this process. Since locales file is going to go through the PR anyway, perhaps allow contributors to submit changes?

**Comment by adam3smith** [comment]
We will look at fixing the CI tests, but note that "leads to failed CI test" does not mean "is not allowed/accepted". It really just means that automated tests are failing. The PR with the modified locales.json looked fine.

**Comment by neha-sri** [comment]
Ok thanks, wasn't sure if there was a reason behind not allowing locales.json and/or if it was enforced. Will resubmit with those changes.

**Comment by adam3smith** [comment]
Thanks and sorry for the hassle -- obviously the CI is intended to help and not confuse. We recently changed some things and are still ironing out the kinks. I'll change the title of your issue to clarify what needs fixing.

**Comment by neha-sri** [comment]
Thanks. Resubmitted #216

**Comment by rmzelle** [comment]
I believe this is already fixed in the latest version of our test infrastructure (see also https://github.com/citation-style-language/styles/issues/5263 and https://github.com/citation-style-language/Sheldon/commit/643bc557611190e800b27cc58ee3d33a74cc381e).
