### ISSUE TITLE
There is no neutral gender-specific ordinals

### ISSUE THREAD

**Issue by ABohdana** [citation-style-language/locales#219]
Hi!

I've been trying to redo the _localisation file for the Ukrainian language_ since the current translation, unfortunately, doesn't meet my requirements.

Among other issues, I discovered one brutal: there is no _neutral gender_.

It is a problem because **the Ukrainian language is fusional** (links between words are expressed through the form of the word), unlike English, which is analytical and uses additional words for that purpose. The numerals we use for enumeration are more adjectives than nouns and therefore inflect in gender, case, and even number. There are _3 genders_ in Ukrainian: **masculine, feminine, and neutral**. The last one is not available in the code - the reason I'm writing to you. 

Could you please help me to find any kind of solution?

Below there is the code I wrote. The other problem I found - no one seems to cite opus or folio much, but such types of documents I never found here, for example, thesis (dissertation). I would be happy to be wrong.

Best wishes
Bohdana

[locales-uk-UA.txt](https://github.com/citation-style-language/locales/files/6095525/locales-uk-UA.txt)

**Comment by fbennett** [comment]
There is no explicit "neuter" attribute value, but a term without gender
specified is used as the neuter firm.

See
https://docs.citationstyles.org/en/1.0.1/specification.html#gender-specific-ordinals

**Comment by ABohdana** [comment]
Oh, I'm really sorry, read it a couple of times and didn't see it.
Now I found all I needed. Thanks!
