### ISSUE TITLE
Plural pages in pt-br should be "pp." and not "p."

### ISSUE THREAD

**Issue by guicalmeida** [citation-style-language/locales#222]
The translation overides CSL settings. Multiple pages should look like  _pp. 125-127_ and not p. _125-127_

**Comment by adam3smith** [comment]
It's possible to override this in a given style, but my understanding is that ABNT, by far the most prominent citation norm in Brazil, uses p., so this would seem to make sense as the default option. 
(See e.g. https://connect.ebsco.com/s/article/Citing-Articles-in-ABNT-Style?language=en_US in English and http://biblioteca.fecap.br/wp-content/uploads/2016/05/Manual-ABNT-regras-gerais-de-estilo-e-formata%C3%A7%C3%A3o-de-trabalhos-acad%C3%AAmicos1.pdf in Portuguese)
Where is it causing issues?

**Comment by adam3smith** [comment]
I'm happy to re-open this if you get back to us, but for now I believe the current version is correct and will close
