### ISSUE TITLE
Advanced functional materials reference output

### ISSUE THREAD

**Issue by 3kpfamily** [citation-style-language/locales#224]
In Mendeley reference manager, I am trying to follow the " Advanced functional materials" citation style. In this citation style, the reference format should be 1. A. B. Author 1, C. D. Author 2, Adv. Mater. 2020, 18, 2001086. But in my case, I only can get 1. A. B. Author 1, C. D. Author 2, Advanced Materials 2020, 18, 2001086. Can anybody help me to solve this issue?
for reference: I have attached author guidelines from advanced functional materials:
https://onlinelibrary.wiley.com/page/journal/16163028/homepage/author-guidelines

**Comment by adam3smith** [comment]
This isn't the right place; let's keep this in the original issue you created: https://github.com/citation-style-language/styles/issues/5396
