### ISSUE TITLE
Duplicate terms: "book", "chapter", etc

### ISSUE THREAD

**Issue by zepinglee** [citation-style-language/locales#268]
I just find `book` and `chapter` terms are used as both item types and locators in locale files. For example:

https://github.com/citation-style-language/locales/blob/62dcca65d754b5e603750838e909a5e90c32e3cc/locales-en-US.xml#L108

https://github.com/citation-style-language/locales/blob/62dcca65d754b5e603750838e909a5e90c32e3cc/locales-en-US.xml#L248-L251

The duplicate term definition may cause unexpected result in citeproc output. Here is the full list of duplicate terms: `interview`, `book`, `chapter`, `book,form:short`, and `chapter,form:short`.

Additionally, PR #254 fixed missing `form="short"` attribute in only `en-US` and `en-GB` but the missing attributes in other languages cause duplicates. I'm happy to make a PR to resolve them.

**Comment by bwiernik** [comment]
Ah, yeah, that's right. They should be removed from the item types list and a note like the one for figure added in their places

**Comment by bwiernik** [comment]
Not sure what you mean. If they are defined in the other locales, they should be removed there too

**Comment by denismaier** [comment]
Sure. But can we automate this process?

**Comment by denismaier** [comment]
Yes. I don't remember, but was there a specific reason we did not do that for `figure`?

**Comment by zepinglee** [comment]
> The item type and locator "figure" are literally the same object. The same would apply to chapter presumably. Book, I'm not sure--in German, if I cited "author, year, Book 2" is that the same term as for "a book"?

It seems that the "book" locator is only used in legal areas like `article` in  (e.g., [Civil Code of China](https://sclx.pkulaw.com/en_law/aa00daaeb5a4fe4ebdfb.html)).

**Comment by denismaier** [comment]
> The item type and locator "figure" are literally the same object. The same would apply to chapter presumably. Book, I'm not sure--in German, if I cited "author, year, Book 2" is that the same term as for "a book"?

You mean as "a book" as opposed to e.g. "a webpage"? Then yes, it would be "Buch" in both cases.

**Comment by denismaier** [comment]
But that should be solved by #269 right?
