### ISSUE TITLE
Localizing placenames and thesis genres etc.

### ISSUE THREAD

**Issue by mknurs** [citation-style-language/locales#273]
Is it possible to specify translations of placenames or thesis genres in the locale files?

If a `bibliography.yaml` has an entry:
```
publisher-place: London
```
Can for example Pandoc then render the citation either *London* or *Londra* etc. based on the language of the article it is being rendered in?

**Comment by adam3smith** [comment]
No, sorry. That'd require a massive database, a local, user-generated database, or hooking into automated translation engines, and we don't plans for any of these at least in the medium run.

**Comment by bwiernik** [comment]
This is something you could potentially do as a pandoc filter (eg, to preprocess your CSL YAML data)
