### ISSUE TITLE
Recent changes in the en_US locale break several tests in the CSL test suite

### ISSUE THREAD

**Issue by andras-simonyi** [citation-style-language/locales#299]
Dear All, I've just noticed that commit #298 (Add missing terms to en-US and alphabetize) seems to break a significant number (~30) of tests in the CSL test suite on citeproc-el, because many used styles rely on some terms not being available, most notably the author verb role form. (I've not yet tried to run those tests on other processors, but I expect them to be broken on other conformant implementations too.)  Are there any plans to update the tests in question (and perhaps styles that also became problematic) to make them compatible with the locale changes?

**Comment by bwiernik** [comment]
Can you link to the tests that are failing?

**Comment by andras-simonyi** [comment]
Thanks for the prompt response -- on closer inspection it looks like the problem must be on the citeproc-el side, apologies  for the noise. (I'm closing the ticket.)

**Comment by bwiernik** [comment]
Let us know if you notice any additional issues

**Comment by zepinglee** [comment]
There are 43 failed tests in citeproc-js with updated locales (see [zepinglee/citeproc-js/actions/runs/8198951140](https://github.com/zepinglee/citeproc-js/actions/runs/8198951140/job/22423295856) and expand the "cslrun -a --reporter spec" step). 6 of them are in the standard test-suite.

@andras-simonyi I suggest checking out the 6b0cb46 commit of [locales](https://github.com/citation-style-language/locales) for testing purpose which is used in current citeproc-js.

**Comment by andras-simonyi** [comment]
@zepinglee thanks, meanwhile I've found and fixed a bug in citeproc-el's term lookup code but the following CSL suite tests are still failing because of the changes both in citeproc-el and citeproc-js:

- fullstyles-chicago-article-title-question
- label-missing-returns-empty
- sort-chicago-year-suffix1
- sort-chicago-year-suffix2

One of the reasons seems to be that the "contributors" macro in the Chicago versions used in the tests contains

    <label form="verb-short" prefix=", " suffix="." text-case="lowercase" />

which is now rendered as "by" for the author variable instead of the earlier empty rendering.

**Comment by bwiernik** [comment]
I've fixed those tests and they should pass now. (For the case of the Chicago style tests, they were incorrectly using `verb-short` when they should have been using `short`)
