### ISSUE TITLE
New terms : "no place" and "no publisher"

### ISSUE THREAD

**Issue by gracile-fr** [citation-style-language/locales#85]
I've found some <a href="http://xbiblio-devel.2463403.n2.nabble.com/Publishers-td5926738.html">old</a> <a href="http://xbiblio-devel.2463403.n2.nabble.com/More-terms-td5927165.html">discussions </a>mentioning them. It has been raised again <a href="http://www.vingtseptpointsept.fr/2014/07/30/zotero-et-les-styles-de-citation-episode-3-un-nouveau-style-iso-690-note/">there</a> (scroll down to "Limites et points à régler") about ISO 690.
@rmzelle ? @adam3smith ?

**Comment by denismaier** [comment]
This can be closed. The terms have been added to 1.0.2
