### ISSUE TITLE
Define primary dialects

### ISSUE THREAD

**Issue by rmzelle** [citation-style-language/locales#99]
As raised at https://github.com/zotero/zotero/pull/623#issuecomment-73773170, we should clearly define the primary dialects for each language tag, as described in the CSL specification: http://citationstyles.org/downloads/specification.html#locale-fallback

We can put this information locales.json, but we'd have to restructure it a bit. Maybe the following works?:

```
{
    "locales": {
        "de-AT": [
            "Deutsch (Österreich)",
            "German (Austria)"
        ],
        "de-CH": [
            "Deutsch (Schweiz)",
            "German (Switzerland)"
        ],
        "de-DE": [
            "Deutsch (Deutschland)",
            "German (Germany)"
        ],
        "en-GB": [
            "English (UK)",
            "English (UK)"
        ],
        "en-US": [
            "English (US)",
            "English (US)"
        ]
    },
    "primary-dialects": {
        "de": "de-DE",
        "en": "en-US"
    }
}
```

**Comment by rmzelle** [comment]
@fbennett, are these fallbacks currently hardcoded in citeproc-js?

**Comment by gracile-fr** [comment]
They seem to be hardcoded, cf. <a href="https://bitbucket.org/fbennett/citeproc-js/src/b61da07586f235db0c973cb699ef1b61828d9ab2/citeproc.js?at=default#cl-394">Lang_Bases</a> and <a href="https://bitbucket.org/fbennett/citeproc-js/src/b61da07586f235db0c973cb699ef1b61828d9ab2/citeproc.js?at=default#cl-4771">CSL.localeResolve</a>.

**Comment by rmzelle** [comment]
Great, thanks for checking!

**Comment by rmzelle** [comment]
@cpina, I created a branch with a slightly modified locales.json. Does it give any problems for you if I merge this?

https://github.com/citation-style-language/locales/commit/7d4cdb1f2d071c30c3b244d41f4746a3948ce79f

**Comment by cpina** [comment]
Thanks @rmzelle , go for it!
